### ISSUE TITLE
Upgrade `schemas/job-conf.yml`

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#310]
# Overview

The newest versions of `goodtables-py` should support more comprehensive config sets e.g. we should be able to have in `goodtables.yml`:

```
datapackages:
  - sources: path
    skip_checks:
        - duplicate_rows
``` 

Also it's clear that we miss some global settings like `skip_checks` (`checks` in a form of dict is deprecated by `goodtables-py`)

related to #303
