### ISSUE TITLE
goodtables.yml [2.5d]

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#6]
# Description

We'll need a `goodtables.yml` parser, which takes the file or a link to a remotely accessible one and returns a list of configuration options, including:

* Fully resolved paths or links to tabular files.
* Schemas to be used
* (optional for MVP) Other configuration options: eg checks to run, etc

Example configuration:

```
# .goodtables.yml

# everything that is tabular
files: '*'

# everything that is csv
files: '*.csv'

# everything that is tabular in a certain directory
files: 'data/*'

# specifics
files:
  -
    path: 'budget.csv'
    schema: 'schemas/budget.json'
  -
    path: 'budget2.csv'
    schema: 'schemas/budget.json'
  -
    path: 'companies.csv'
```

Once the API has dropped a payload to S3 or some filesystem, then in order to run a job that is basically a good tables batch run, we need to have parsed the spec file and generated a list of paths to files for use in that batch.

# Tasks

- [ ] Define the parameters needed for the validation job to run (ie the outputs of parsing `.goodtables.yml`)
- [ ] Write a YML spec for how to model these parameters
- [ ] Implement the parser

# Estimate

3
